# Generated by Django 4.1.4 on 2022-12-14 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="professor", name="user",),
        migrations.AddField(
            model_name="dicas",
            name="professor",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.professor",
            ),
        ),
    ]
