# Generated by Django 4.1.4 on 2022-12-14 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_professor_user_dicas_professor"),
    ]

    operations = [
        migrations.AddField(
            model_name="professor",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
