# Generated by Django 4.1.4 on 2022-12-14 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_professor_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="dicas", name="professor",),
    ]
