# Generated by Django 4.1.4 on 2022-12-15 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_dicas_professor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Esporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Plano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=100)),
                (
                    "aluno",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.aluno"
                    ),
                ),
                (
                    "competicao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.competicao"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Treino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=100)),
                ("dia", models.DateField()),
                (
                    "plano",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.plano"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Performance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tempo", models.IntegerField()),
                ("quilometragem", models.IntegerField()),
                ("esforco", models.CharField(max_length=20)),
                (
                    "aluno",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.aluno"
                    ),
                ),
                (
                    "treino",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.treino"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evolucao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=100)),
                (
                    "aluno",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.aluno"
                    ),
                ),
                (
                    "treino",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="api.treino"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="competicao",
            name="esporte",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.esporte"
            ),
        ),
        migrations.AddField(
            model_name="dicas",
            name="evolucao",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.evolucao",
            ),
        ),
    ]
