# Generated by Django 4.1.4 on 2022-12-15 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_competicao_esporte_plano_treino_performance_evolucao_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="dicas", name="title",),
    ]
