# Generated by Django 4.1.4 on 2022-12-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_dicas_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treino", name="descricao", field=models.TextField(),
        ),
    ]
